#!/bin/bash

if [[ $EUID -ne 0 ]]; then
	echo "This script must be run as root."
	exit 1
fi

export PATH="$PATH:/usr/local/sbin:/sbin:/usr/sbin"

cd "$(dirname ${BASH_SOURCE[0]})"
iptables-restore < rules.v4 && echo 'applied IPv4 rules'
ip6tables-restore < rules.v6 && echo 'applied IPv6 rules'
