#!/bin/bash
if [[ -z "$1" || "$1" == "all" ]]; then
	packages=$(find . -maxdepth 1 -mindepth 1 -type d ! -name '.git')
else
	packages="$@"
fi

echo Packages to build: $packages

shift
for dir in $packages; do
	cd $dir
	echo BUILDING: $dir
	dpkg-buildpackage -us -uc
	cd ..
done
