#!/bin/bash
trap 'exit 1' INT TERM

cd "$(dirname "${BASH_SOURCE[0]}")"
if [[ -z "$1" || "$1" == "all" ]]; then
	PACKAGES=$(find . -maxdepth 1 -mindepth 1 -type d ! -name '.git')
else
	PACKAGES="$@"
fi

echo "Packages to build: $PACKAGES"

SUCCESSES=()
FAILURES=()
for pkg in $PACKAGES; do
	pushd "$pkg"
	pkg="$(basename "$pkg")"
	echo
	echo "BUILDING: $pkg"
	echo
	dpkg-buildpackage -us -uc && SUCCESSES+=("$pkg") || FAILURES+=("$pkg")
	popd
done

echo "${#SUCCESSES[@]} packages built successfully: ${SUCCESSES[@]}"
echo "${#FAILURES[@]} packages failed to build: ${FAILURES[@]}"
exit ${#FAILURES[@]}
