#!/bin/bash
# installability checker for utopia-packages
set -e
cd "${0%/*}"

DIST="$1"
if [[ -z "$DIST" ]]; then
    echo "usage: $0 <dist>"
    exit 1
fi

eval "$(dpkg-architecture -s)"  # source Debian build args

echo "Fetching Debian packages list..."
wget "https://deb.debian.org/debian/dists/${DIST}/main/binary-${DEB_HOST_ARCH}/Packages.xz" -O- | unxz -c > Packages-Debian-main

apt-ftparchive packages . > Packages
dose-debcheck --fg Packages -e -f --summary --bg Packages-Debian-main
