Document: utopia-mate-defaults
Title: Debian utopia-mate-defaults Manual
Author: <insert document author here>
Abstract: This manual describes what utopia-mate-defaults is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/utopia-mate-defaults/utopia-mate-defaults.sgml.gz

Format: postscript
Files: /usr/share/doc/utopia-mate-defaults/utopia-mate-defaults.ps.gz

Format: text
Files: /usr/share/doc/utopia-mate-defaults/utopia-mate-defaults.text.gz

Format: HTML
Index: /usr/share/doc/utopia-mate-defaults/html/index.html
Files: /usr/share/doc/utopia-mate-defaults/html/*.html
